frontend/Models/Departamento.cs
using System;

namespace frontend.Models
{
    public class Departamento
    {
        public int IdDepartamento { get; set; } 
        public string NombreDepartamento { get; set; } = null!;

        public Departamento()
        {
        }
    }

}

frontend/Controllers/DepartamentoController.cs
using frontend.Models;
using Microsoft.AspNetCore.Mvc;
using frontend.Interfaces;
using frontend.Services;
using System.Net;

namespace frontend.Controllers 
{
    
    public class DepartamentoController: Controller
    {
        private IDepartamentoService _service;
      
        public DepartamentoController(IDepartamentoService service)
        {
           _service = service;
        }
        public async Task<IActionResult> Listar()
        {
            var Departamentos = await _service.GetDepartamentos();
            return View(Departamentos);
        }
        
        public  IActionResult Guardar()
        {
            return View();
        }
        
        [HttpPost]
        public async Task<IActionResult> Guardar(Departamento departamento)
        {
            
            if(!ModelState.IsValid){
                return View();
            }
            try
            {
                
                HttpResponseMessage response = await _service.CrearDepartamento(departamento);
                
                if (response.StatusCode == HttpStatusCode.Created)
                        {
                            // La solicitud fue exitosa
                            var content = await response.Content.ReadAsStringAsync();
                            // Aquí puedes procesar la respuesta como desees
                            ViewBag.SuccessMessage = "Solicitud POST exitosa. Respuesta del servidor: " + content;
                                return RedirectToAction("Listar");
                        }
                        else
                        {
                            // La solicitud no fue exitosa, manejar el error
                                Console.WriteLine("Error en la solicitud POST, contacte al administrador. Código de estado: " + response.StatusCode);
                                return View();
                        }
            } catch (Exception ex) 
            {
                
                // Error en la solicitud
                Console.WriteLine("Error al realizar la solicitud POST, contacte al administrador:");
                Console.WriteLine(ex.Message);
            }
            
            return View();
        }

        public async Task<IActionResult> Editar(int id)
        {
            var DepartamentoToUpdate = await _service.GetDepartamentoById(id);
            return View(DepartamentoToUpdate);
        }

        [HttpPost]
        public async Task<IActionResult> Editar(int id, Departamento Departamento)
        {
            if(!ModelState.IsValid){
                Console.WriteLine("Modelo no valido.");
                return View();
            }

            Console.WriteLine("Voy al servicio a actualizar el departamento.");
            var respuesta = await _service.ActualizarDepartamento(id, Departamento);

            if(respuesta.IsSuccessStatusCode)
            {
                Console.WriteLine("Exito");
                return RedirectToAction("Listar");
            }
            else
                Console.WriteLine("Solicitud fallida.");
                return View();
        }

        public async Task<IActionResult> Eliminar(int Id)
        {
            var departamento = await _service.GetDepartamentoById(Id);
            return View(departamento);
        }

        [HttpPost]
        public async Task<IActionResult> Eliminar(int Id, Departamento departamento)
        {
           
            await Task.Delay(2000);
            Console.WriteLine($"tipo id: {Id.GetType()}");
            var respuesta = await _service.EliminarDepartamento(Id);

            if(respuesta.IsSuccessStatusCode)
                return RedirectToAction("Listar");
            else
                return View();
        }

    }

}

frontend/Views/Departamento/Editar.cshtml
@model frontend.Models.Departamento
@{
    ViewData["Title"] = "Guardar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
  <h5 class="card-header">Edicion de Departamentos</h5>
  <div class="card-body">
    <form asp-action="Editar" asp-controller="Departamento" method="post"> 

        <div class="mb-3">
            <label for="nombreDepartamento" class="form-label">Nombre del departamento</label>
            <input asp-for="NombreDepartamento" type="text" class="form-control" id="nombreDepartamento">
            <span asp-validation-for="NombreDepartamento" class="text-danger"></span>
        </div>

        <button type="submit" class="btn btn-primary me-2"><i class="bi bi-person-check me-1"></i>Guardar</button>
        <a asp-action="Listar" asp-controller="Departamento" class="btn btn-secondary"><i class="bi bi-arrow-90deg-left me-1"></i>Volver a la lista</a>
    </form>
    
    @{
        if (@ViewBag.ErrorMessage != null)
        {
            <div class="alert alert-danger" role="alert">
                @ViewBag.ErrorMessage
            </div>
        
        } else if (@ViewBag.SuccessMessage != null)
        {
            <div class="alert alert-success" role="alert">
                @ViewBag.ErrorMessage
            </div>
        }
        
    }
    
  </div>
</div>

frontend/Views/Departamento/Eliminar.cshtml
@model Departamento
@{
   ViewData["Title"] = "Eliminar";
   Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
  <h5 class="card-header">Eliminar Departamento</h5>
  <div class="card-body">

    <form asp-action="Eliminar" asp-controller="Departamento" method="post">

        <input asp-for="IdDepartamento" type="hidden" class="form-control" readonly>

        <div class="alert alert-danger" role="alert">
        Desea eliminar el siguiente Departamento de la base de datos?
            <p>
                @if (Model != null){
                    <b>ID #:</b> @Model.IdDepartamento <br>
                    <b>Nombre:</b> @Model.NombreDepartamento <br>  
                } else{
                    <p><b>Hubo un error trayendo los datos</b></p>
                }        
            </p>
        </div>
        
        <button type="submit" class="btn btn-danger me-2"><i class="bi bi-person-check me-1"></i>Eliminar</button>
        <a asp-action="Listar" asp-controller="Departamento" class="btn btn-secondary"><i class="bi bi-arrow-90deg-left me-1"></i>Volver a la lista</a>
    </form>
  </div>
</div>

frontend/Views/Departamento/Guardar.cshtml
@model frontend.Models.Departamento
@{
    ViewData["Title"] = "Guardar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
  <h5 class="card-header">Registro de nuevos Departamentos</h5>
  <div class="card-body">
    <form asp-action="Guardar" asp-controller="Departamento" method="post"> 

        <div class="mb-3">
            <label for="nombreDepartamento" class="form-label">Nombre del departamento</label>
            <input asp-for="NombreDepartamento" type="text" class="form-control" id="nombreDepartamento">
            <span asp-validation-for="NombreDepartamento" class="text-danger"></span>
        </div>

        <button type="submit" class="btn btn-primary me-2"><i class="bi bi-person-check me-1"></i>Guardar</button>
        <a asp-action="Listar" asp-controller="Departamento" class="btn btn-secondary"><i class="bi bi-arrow-90deg-left me-1"></i>Volver a la lista</a>
    </form>
    
   
  </div>
</div>

frontend/Views/Departamento/Listar.cshtml
@model List<Departamento>
@{
   ViewData["Title"] = "Lista de Departamentos";
   Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
  <h5 class="card-header">Departamentos</h5>
  <div class="card-body">
    <a asp-action="Guardar" asp-controller="Departamento" class="btn btn-success"><i class="bi bi-person-plus me-1"></i>Agregar Departamento</a>
    <hr/>
    <table class="table table-responsive"> 
      <thead>
         <tr>
            <th>ID</th>
            <th>Nombre del Despartamento</th>
            <th> </th>
         </tr>
      </thead>
      <tbody>
         @foreach (var item in Model)
         {
            <tr>
               <td>@item.IdDepartamento</td>
               <td >@item.NombreDepartamento</td>
               <td class="text-center">
                  <a asp-action="Editar" asp-controller="Departamento" class="btn btn-primary btn-sm me-2" asp-route-Id = "@item.IdDepartamento"><i class="bi bi-pencil me-1"></i>Editar</a>
                  <a asp-action="Eliminar" asp-controller="Departamento" class="btn btn-danger btn-sm" asp-route-Id = "@item.IdDepartamento"><i class="bi bi-x-circle"></i> Eliminar</a>
               </td>
            </tr>
             
         }
      </tbody>
    </table>
    
  </div>
</div>