frontend/Models/Puesto.cs
using System;

namespace frontend.Models
{
    public class Puesto
    {
        public int IdPuestoEmpleado { get; set; }
        public string NombrePuesto { get; set; } = null!;
        public string Descripcion { get; set; } = null!;
        public int IdDepartamento { get; set; }
    }
}

frontend/Controllers/PuestoController.cs
using frontend.Models;
using Microsoft.AspNetCore.Mvc;
using frontend.Interfaces;
using frontend.Services;

namespace frontend.Controllers 
{
    
    public class PuestoController: Controller
    {
        private IPuestoService _service;
        private IDrpLstPuesto _drpLst;
    
        public PuestoController(IPuestoService service, IDrpLstPuesto drpLst)
        {
           _service = service;
           _drpLst = drpLst;
        }
        public async Task<IActionResult> Listar()
        {
            var puestos = await _service.GetAllPuestos();
            var departamentos = await _drpLst.GetDepartamentosForDropdown();
            await Task.Delay(2000);
            ViewBag.Departamentos = departamentos;
            return View(puestos);
        }
        
        public  async Task<IActionResult> Guardar()
        {
           
            var departamentos = await _drpLst.GetDepartamentosForDropdown();
            ViewBag.Departamentos = departamentos;
            await Task.Delay(2000);
            return View();
        }
        
        [HttpPost]
        public async Task<IActionResult> Guardar(Puesto puesto)
        {
            
            if(!ModelState.IsValid){
                return View();
            }
            try
            {
               
                HttpResponseMessage response = await _service.CreatePuesto(puesto);
                await Task.Delay(2000);
                var content = "";
                if (response.IsSuccessStatusCode)
                        {
                            // La solicitud fue exitosa
                            content = await response.Content.ReadAsStringAsync();
                            // Aquí puedes procesar la respuesta como desees
                            ViewBag.SuccessMessage = "Solicitud POST exitosa. Respuesta del servidor: " + content;
                                return RedirectToAction("Listar");
                        }
                        else
                        {
                            ViewBag.ErrorMessage = "Error: la solicitud fue completada con errores, contacte al administrador. Código de estado: " + response.StatusCode;
                            return View();
                        }
            } catch (Exception ex) 
            {
                
                // Error en la solicitud
                ViewBag.ErrorMessage = "Error al realizar la solicitud POST, contacte al administrador: " + ex.Message;
                Console.WriteLine("Error en la solicitud:", ex.Message);
            }
            
            return View();
        }

        public async Task<IActionResult> Editar(int id)
        {
            var puestoToUpdate = await _service.GetPuestoById(id);
            await Task.Delay(2000); 
            var departamentos = await _drpLst.GetDepartamentosForDropdown();
            ViewBag.Departamentos = departamentos;
            return View(puestoToUpdate);
        }

        [HttpPost]
          public async Task<IActionResult> Editar(int id, Puesto puesto)
        {
            if(!ModelState.IsValid){
                return View();
            }

            var respuesta = await _service.UpdatePuesto(id, puesto);

            if(respuesta.IsSuccessStatusCode)
                return RedirectToAction("Listar");
            else
                return View();
        }
        public async Task<IActionResult> Eliminar(int id)
        {
            var puesto = await _service.GetPuestoById(id);
            Console.WriteLine(puesto.IdPuestoEmpleado);
            return View(puesto);
        }

        [HttpPost]
        public async Task<IActionResult> Eliminar(Puesto puesto)
        {
            var respuesta = await _service.DeletePuesto(puesto.IdPuestoEmpleado);

             if(respuesta.IsSuccessStatusCode)
                return RedirectToAction("Listar");
            else
                return View();
        }

    }

}

frontend/Views/Puesto/Editar.cshtml
@model Puesto
@{
   ViewData["Title"] = "Editar puesto";
   Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
  <h5 class="card-header">Editar datos del puesto</h5>
  <div class="card-body">

    <form asp-action="Editar" asp-controller="Puesto" method="post">
        <div class="mb-3">
            <label for="nombrePuesto" class="form-label">Nombre del Puesto</label>
            <input asp-for="NombrePuesto" type="text" class="form-control" id="nombrePuesto">
            <span asp-validation-for="NombrePuesto" class="text-danger"></span>
        </div>
        
        <div class="form-group">
            <label asp-for="IdDepartamento">Departamento</label>
            <select asp-for="IdDepartamento" asp-items="ViewBag.Departamentos" class="form-control">
                <option value=@ViewBag.Departamentos selected>Seleccionar un puesto</option>
            </select>
        </div>

        <div class="mb-3">
            <label for="descripcion" class="form-label">Descripcion</label>
            <input asp-for="Descripcion" type="text" class="form-control" id="descripcion">
            <span asp-validation-for="Descripcion" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary me-2"><i class="bi bi-person-check me-1"></i>Guardar</button>
        <a asp-action="Listar" asp-controller="Puesto" class="btn btn-secondary"><i class="bi bi-arrow-90deg-left me-1"></i>Volver a la lista</a>
    </form>
  </div>
</div>

frontend/Views/Puesto/Eliminar.cshtml
@model Puesto
@{
   ViewData["Title"] = "Eliminar";
   Layout = "~/Views/Shared/_Layout.cshtml";
   ViewData["BodyId"] = "appointment-body";
}

<div class="card">
  <h5 class="card-header">Eliminar Puesto</h5>
  <div class="card-body">

    <form asp-action="Eliminar" asp-controller="Puesto" method="post">

        <input asp-for="IdPuestoEmpleado" type="hidden" class="form-control">

        <div class="alert alert-danger" role="alert">
        Desea eliminar al siguiente empleado de la base de datos?
            <p>
                <b>ID #:</b> @Model.IdPuestoEmpleado<br>
                <b>Nombre del puesto:</b> @Model.NombrePuesto<br>
                <b>Departamento al que pertenece:</b> @Model.IdDepartamento <br>
                <b>Descripcion:</b> @Model.Descripcion <br>
                <b>
            </p>
        </div>
        
        <button type="submit" class="btn btn-danger me-2"><i class="bi bi-person-check me-1"></i>Eliminar</button>
        <a asp-action="Listar" asp-controller="Puesto" class="btn btn-secondary"><i class="bi bi-arrow-90deg-left me-1"></i>Volver a la lista</a>
    </form>
  </div>
</div>

frontend/Views/Puesto/Guardar.cshtml
@model frontend.Models.Puesto
@{
    ViewData["Title"] = "Guardar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
  <h5 class="card-header">Registro de nuevos Puestos</h5>
  <div class="card-body">
    <form asp-action="Guardar" asp-controller="Puesto" method="post"> 
        <div class="mb-3">
            <label for="nombrePuesto" class="form-label">Nombre del Puesto</label>
            <input asp-for="NombrePuesto" type="text" class="form-control" id="nombrePuesto">
            <span asp-validation-for="NombrePuesto" class="text-danger"></span>
        </div>
        
        <div class="form-group">
            <label asp-for="IdDepartamento">Departamento</label>
            <select asp-for="IdDepartamento" asp-items="ViewBag.Departamentos" class="form-control">
                <option value="">Seleccionar un puesto</option>
            </select>
        </div>

        <div class="mb-3">
            <label for="descripcion" class="form-label">Descripcion</label>
            <input asp-for="Descripcion" type="text" class="form-control" id="descripcion">
            <span asp-validation-for="Descripcion" class="text-danger"></span>
        </div>

        <button type="submit" class="btn btn-primary me-2"><i class="bi bi-person-check me-1"></i>Guardar</button>
        <a asp-action="Listar" asp-controller="Puesto" class="btn btn-secondary"><i class="bi bi-arrow-90deg-left me-1"></i>Volver a la lista</a>
    </form>
    
    @{
        if (@ViewBag.ErrorMessage != null)
        {
            <div class="alert alert-danger" role="alert">
                @ViewBag.ErrorMessage
            </div>
        
        } else if (@ViewBag.SuccessMessage != null)
        {
            <div class="alert alert-success" role="alert">
                @ViewBag.ErrorMessage
            </div>
        }
        
    }
    
  </div>
</div>

frontend/Views/Puesto/Listar.cshtml
@model List<Puesto>
@{
   ViewData["Title"] = "Lista de empleados";
   Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
  <h5 class="card-header">Puestos</h5>
  <div class="card-body">
    <a asp-action="Guardar" asp-controller="Puesto" class="btn btn-success"><i class="bi bi-person-plus me-1"></i>Puestos de trabajo</a>
    <hr/>
    <table class="table table-responsive"> 
      <thead>
         <tr>
            <th>ID</th>
            <th class="text-center">Nombre del puesto</th>
            <th class="text-center">Departamento correspondiente</th>
            <th class="text-center">Descripcion</th>
            <th></th>
         </tr>
      </thead>
      <tbody>
         @foreach (var item in Model)
         {
            <tr>
               <td class="text-center">@item.IdPuestoEmpleado</td>
               <td class="text-center">@item.NombrePuesto</td>
               <td class="text-center">
                  @{
                     var idDepartamento = item.IdDepartamento.ToString();
                     var departamento = ViewBag.Departamentos as List<SelectListItem>;
                     var DepartamentoItem = departamento.Find(p => p.Value == idDepartamento);
                     if (DepartamentoItem != null)
                     {
                           @DepartamentoItem.Text
                     }
                     else
                     {
                           <span>Sin Departamento asignado</span>
                     }
                  }
               </td>
               <td class="text-center">@item.Descripcion</td>
               <td class="text-center">
                  <a asp-action="Editar" asp-controller="Puesto" class="btn btn-primary btn-sm me-2 mb-2" asp-route-Id = "@item.IdPuestoEmpleado"><i class="bi bi-pencil me-1"></i>  Editar</a>
                  <a asp-action="Eliminar" asp-controller="Puesto" class="btn btn-danger btn-sm" asp-route-Id = "@item.IdPuestoEmpleado"><i class="bi bi-x-circle"></i> Eliminar</a>
               </td>
            </tr>
             
         }
      </tbody>
    </table>
    
  </div>
</div>