frontend/Models/Empleado.cs
using System;
using Newtonsoft.Json;

namespace frontend.Models
{
    public class Empleado
    {
    public int Id { get; set; } 
    public string Nombre { get; set; } = null!;
    public string CorreoElectronico { get; set; }= null!;

    [JsonProperty("NumeroTelefono")]
    public string NumeroTelefono { get; set; } = null!;
    public DateTime FechaNacimiento { get; set; }
    public DateTime FechaIngreso { get; set; }
    public int IdPuestoEmpleado { get; set; }
    public bool Activo { get; set; }

    public Empleado()
    {}
    }

}

frontend/Controllers/EmpleadoController.cs
using frontend.Models;
using Microsoft.AspNetCore.Mvc;
using frontend.Interfaces;
using frontend.Services;

namespace frontend.Controllers 
{
    
    public class EmpleadoController: Controller
    {
        private IEmpleadoService _service;
        private IDrpLstEmpleado _drpLst;
        public EmpleadoController(IEmpleadoService service, IDrpLstEmpleado drpLst)
        {
           _service = service;
           _drpLst = drpLst;
        }
        public async Task<IActionResult> Listar()
        {
            var empleados = await _service.GetEmpleados();
            await Task.Delay(2000);
            var puestos = await _drpLst.GetPuestosForDropdown();
            ViewBag.Puestos = puestos;
            return View(empleados);
        }
        
        public async  Task<IActionResult> Guardar()
        {
            try
            {

                var puestos = await _drpLst.GetPuestosForDropdown();
                ViewBag.Puestos = puestos;
                return View();
                
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }

            return View();
            
        }
        
        [HttpPost]
        public async Task<IActionResult> Guardar(Empleado empleado)
        {
            Console.WriteLine($"Id:{empleado.Id}\nNombre:{empleado.Nombre}\nIdPuestoEmpleado:{empleado.IdPuestoEmpleado}");
            if(!ModelState.IsValid){
                return View();
            }

            try
            {
                
                HttpResponseMessage response = await _service.CrearEmpleado(empleado);
                
                if (response.StatusCode == System.Net.HttpStatusCode.Created )
                        {
                            // La solicitud fue exitosa
                            var content = await response.Content.ReadAsStringAsync();
                            // Aquí puedes procesar la respuesta como desees
                            ViewBag.SuccessMessage = "Solicitud POST exitosa. Respuesta del servidor: " + content;
                                return RedirectToAction("Listar");
                        }
                        else
                        {
                            // La solicitud no fue exitosa, manejar el error
                            ViewBag.ErrorMessage = "Error en la solicitud POST, contacte al administrador. Código de estado: " + response.StatusCode;
                                return View();
                        }
            } catch (Exception ex) 
            {
                
                // Error en la solicitud
                ViewBag.ErrorMessage = "Error al realizar la solicitud POST, contacte al administrador: " + ex.Message;
                Console.WriteLine(ex.Message);
            }
            
            return View();
        }

        public async Task<IActionResult> Editar(int Id)
        {
            var empleado = await _service.GetEmpleadoById(Id);
            await Task.Delay(2000);
            var puestos = await _drpLst.GetPuestosForDropdown();
            ViewBag.Puestos = puestos;
            return View(empleado);
        }

        [HttpPost]
        public async Task<IActionResult> Editar(Empleado empleado)
        {
            if(!ModelState.IsValid){
                return View();
            }

            var respuesta = await _service.ActualizarEmpleado(empleado.Id, empleado);
            await Task.Delay(2000);
            if(respuesta.IsSuccessStatusCode)
                return RedirectToAction("Listar");
            else
                return View();
        }

        public async Task<IActionResult> Eliminar(int Id)
        {
            var empleado = await _service.GetEmpleadoById(Id);
            return View(empleado);
        }

        [HttpPost]
        public async Task<IActionResult> Eliminar(Empleado empleado)
        {
            var respuesta = await _service.EliminarEmpleado(empleado.Id);

            if(respuesta.IsSuccessStatusCode)
                return RedirectToAction("Listar");
            else
                return View();
        }

    }

}

frontend/Views/Empleado/Editar.cshtml
@model Empleado
@{
   ViewData["Title"] = "Edicion de datos";
   Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
  <h5 class="card-header">Editar datos del empleado</h5>
  <div class="card-body">

    <form asp-action="Editar" asp-controller="Empleado" method="post">
        <div class="mb-3">
            <label for="nombre" class="form-label">Nombre</label>
            <input asp-for="Nombre" type="text" class="form-control" id="nombre">
            <span asp-validation-for="Nombre" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <label for="correoElectronico" class="form-label">Correo Electronico</label>
            <input asp-for="CorreoElectronico" type="text" class="form-control" id="correoElectronico">
            <span asp-validation-for="CorreoElectronico" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <label for="numeroTelefono" class="form-label">Telefono</label>
            <input asp-for="NumeroTelefono" type="tel" class="form-control" id="numeroTelefono" 
            placeholder="809-245-6782" pattern="[0-9]{3}-[0-9]{3}-[0-9]{4}" required>
            <span asp-validation-for="NumeroTelefono" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label for="fechaNacimiento" class="form-label">Fecha de Nacimiento</label>
            <input asp-for="FechaNacimiento" type="date" class="form-control" id="fechaNacimiento">
            <span asp-validation-for="FechaNacimiento" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label for="fechaIngreso" class="form-label">Fecha de ingreso</label>
            <input asp-for="FechaIngreso" type="date" class="form-control" id="fechaIngreso">
            <span asp-validation-for="FechaIngreso" class="text-danger"></span>
        </div>
        
        <div class="form-group">
            <label asp-for="IdPuestoEmpleado">Puesto</label>
            <select asp-for="IdPuestoEmpleado" asp-items="ViewBag.Puestos" class="form-control">
                <option value="@ViewBag.Puestos" selected>Seleccionar un puesto</option>
            </select>
        </div>

        <div class="form-group">
            <label asp-for="Activo" class="control-label"></label>
            <input asp-for="Activo" type="checkbox" class="form-check-input" />
        </div>
        <button type="submit" class="btn btn-primary me-2"><i class="bi bi-person-check me-1"></i>Guardar</button>
        <a asp-action="Listar" asp-controller="Empleado" class="btn btn-secondary"><i class="bi bi-arrow-90deg-left me-1"></i>Volver a la lista</a>
    </form>
  </div>
</div>

frontend/Views/Empleado/Eliminar.cshtml
@model Empleado
@{
   ViewData["Title"] = "Eliminar";
   Layout = "~/Views/Shared/_Layout.cshtml";
   ViewData["BodyId"] = "appointment-body";
}

<div class="card">
  <h5 class="card-header">Eliminar Empleado</h5>
  <div class="card-body">

    <form asp-action="Eliminar" asp-controller="Empleado" method="post">

        <input asp-for="Id" type="hidden" class="form-control">

        <div class="alert alert-danger" role="alert">
        Desea eliminar al siguiente empleado de la base de datos?
            <p>
                <b>ID #:</b> @Model.Id<br>
                <b>Nombre:</b> @Model.Nombre <br>
                <b>Telefono:</b> @Model.NumeroTelefono <br>
                <b>Fecha de ingreso:</b> @Model.FechaIngreso <br>
                <b>Puesto:</b> @Model.IdPuestoEmpleado <br>
                <b>Correo Electronico:</b> @Model.CorreoElectronico 
            </p>
        </div>
        
        <button type="submit" class="btn btn-danger me-2"><i class="bi bi-person-check me-1"></i>Eliminar</button>
        <button asp-action="Listar" asp-controller="Empleado" class="btn btn-secondary"><i class="bi bi-arrow-90deg-left me-1"></i>Volver a la lista</button>
    </form>
  </div>
</div>

frontend/Views/Empleado/Guardar.cshtml
@model frontend.Models.Empleado
@{
    ViewData["Title"] = "Guardar";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var today = DateTime.Now.ToString("yyyy-MM-dd");
}

<div class="card">
  <h5 class="card-header">Registro de Empleado</h5>
  <div class="card-body">
    <form asp-action="Guardar" asp-controller="Empleado" method="post"> 
        <div class="mb-3">
            <label for="nombre" class="form-label">Nombre</label>
            <input asp-for="Nombre" type="text" class="form-control" id="nombre">
            <span asp-validation-for="Nombre" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <label for="correoElectronico" class="form-label">Correo Electronico</label>
            <input asp-for="CorreoElectronico" type="text" class="form-control" id="correoElectronico">
            <span asp-validation-for="CorreoElectronico" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <label for="numeroTelefono" class="form-label">Telefono</label>
            <input asp-for="NumeroTelefono" type="tel" class="form-control" id="numeroTelefono" 
            placeholder="809-245-6782" pattern="[0-9]{3}-[0-9]{3}-[0-9]{4}" required>
            <span asp-validation-for="NumeroTelefono" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label for="fechaNacimiento" class="form-label">Fecha de Nacimiento</label>
            <input asp-for="FechaNacimiento" type="date" class="form-control" id="fechaNacimiento">
            <span asp-validation-for="FechaNacimiento" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label for="fechaIngreso" class="form-label">Fecha de ingreso</label>
            <input asp-for="FechaIngreso" type="date" class="form-control" id="fechaIngreso">
            <span asp-validation-for="FechaIngreso" class="text-danger"></span>
        </div>
        
        <div class="form-group">
            <label asp-for="IdPuestoEmpleado">Puesto</label>
            <select asp-for="IdPuestoEmpleado" asp-items="ViewBag.Puestos" class="form-control">
                <option value="">Seleccionar un puesto</option>
            </select>
        </div>
        
        <button type="submit" class="btn btn-primary me-2"><i class="bi bi-person-check me-1"></i>Guardar</button>
        <a asp-action="Listar" asp-controller="Empleado" class="btn btn-secondary"><i class="bi bi-arrow-90deg-left me-1"></i>Volver a la lista</a>
    </form>
    
    @{
        if (@ViewBag.ErrorMessage != null)
        {
            <div class="alert alert-danger" role="alert">
                @ViewBag.ErrorMessage
            </div>
        
        } else if (@ViewBag.SuccessMessage != null)
        {
            <div class="alert alert-success" role="alert">
                @ViewBag.ErrorMessage
            </div>
        }
        
    }
    
  </div>
</div>

frontend/Views/Empleado/Listar.cshtml
@model List<Empleado>
@{
   ViewData["Title"] = "Lista de empleados";
   Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
  <h5 class="card-header">Empleados en nomina</h5>
  <div class="card-body">
    <a asp-action="Guardar" asp-controller="Empleado" class="btn btn-success"><i class="bi bi-person-plus me-1"></i>Agregar empleado</a>
    <hr/>
    <table class="table table-responsive"> 
      <thead>
         <tr>
            <th class="text-center">ID</th>
            <th class="text-center">Nombre Completo</th>
            <th class="text-center">Correo Electronico</th>
            <th class="text-center">Tel.</th>
            <th class="text-center">Fecha de ingreso</th>
            <th class="text-center" style="white-space: nowrap">Puesto</th>
            <th style="white-space: nowrap">Activo</th>
            <th style="white-space: nowrap"></th>
         </tr>
      </thead>
      <tbody>
         @foreach (var item in Model)
         {
            <tr>
               <td class="text-center" style="white-space: nowrap">@item.Id</td>
               <td class="text-center" style="white-space: nowrap">@item.Nombre</td>
               <td class="text-center" style="white-space: nowrap">@item.CorreoElectronico</td>
               <td class="text-center" style="white-space: nowrap">@item.NumeroTelefono</td>
               <td class="text-center">@item.FechaIngreso</td>
               <td class="text-center">
                  @{
                     var idPuesto = item.IdPuestoEmpleado.ToString();
                     var puesto = ViewBag.Puestos as List<SelectListItem>;
                     var puestoItem = puesto.Find(p => p.Value == idPuesto);
                     if (puestoItem != null)
                     {
                           @puestoItem.Text
                     }
                     else
                     {
                           <span>Sin puesto</span>
                     }
                  }
               </td>
               <td>
                   @if (item.Activo)
                  {
                     <span class="text-success">Activo</span>
                  }
                  else
                  {
                     <span class="text-danger">Inactivo</span>
                  }
               </td>
               <td class="text-center container-fluid">
                  <a asp-action="Editar" asp-controller="Empleado" class="btn btn-primary btn-sm me-2 mb-2" asp-route-Id = "@item.Id"><i class="bi bi-pencil me-1"></i> Editar </a>
                  <a asp-action="Eliminar" asp-controller="Empleado" class="btn btn-danger btn-sm me-2" asp-route-Id = "@item.Id"><i class="bi bi-x-circle"></i> Eliminar</a>
               </td>
            </tr>
             
         }
      </tbody>
    </table>
    
  </div>
</div>